vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO CediCore/SafePtr
    REF v1.0.0
    SHA512 0
)

file(INSTALL ${SOURCE_PATH}/include DESTINATION ${CURRENT_PACKAGES_DIR})
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/safeptr)
file(INSTALL ${SOURCE_PATH}/README.md DESTINATION ${CURRENT_PACKAGES_DIR}/share/safeptr)
